### ISSUE TITLE
fuse-ext2 not installed: error UTIME_OMIT

### ISSUE THREAD

**Issue by thelabeljoyves** [alperakcan/fuse-ext2#102]
Can't install fuse-ext2:
-installed fuse 3.9.1 on Mac os x 10.12
-made the file in the folder and ran the script from the folder
user/tmp/ext4/
> I get repeatedly following error at the end of the install:

**op_utimens.c:45:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[0].tv_nsec != UTIME_OMIT)
                             ^
op_utimens.c:47:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[1].tv_nsec != UTIME_OMIT)**
                             ^
2 errors generated.
make[2]: *** [fuse_ext2-op_utimens.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Making install in fuse-ext2
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -DHAVE_CONFIG_H -I/usr/local/include -D__FreeBSD__=10 -idirafter/opt/gnu/include -idirafter/usr/local/include/osxfuse/ -MT fuse_ext2-op_utimens.o -MD -MP -MF .deps/fuse_ext2-op_utimens.Tpo -c -o fuse_ext2-op_utimens.o `test -f 'op_utimens.c' || echo './'`op_utimens.c
**op_utimens.c:45:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[0].tv_nsec != UTIME_OMIT)
                             ^
op_utimens.c:47:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[1].tv_nsec != UTIME_OMIT)**
                             ^
2 errors generated.
make[1]: *** [fuse_ext2-op_utimens.o] Error 1
make: *** [install-recursive] Error 1

Then try to run the command for issue report

kaba:ext5 yvesmettler$ cd ..
kaba:tmp yvesmettler$ cd ..
kaba:~ yvesmettler$ /usr/local/bin/fuse-ext2 -v /dev/path /mnt/point -o debug
-bash: /usr/local/bin/fuse-ext2: No such file or directory
kaba:~ yvesmettler$ 

Thanks for help

**Comment by galaind** [comment]
I'm facing the sam problem

**Comment by tkircher** [comment]
UTIME_OMIT isn't defined in MacOS. This is addressed in some other projects. You can include the definitions in fuse-ext2.h:

#ifndef UTIME_NOW
# define UTIME_NOW -1
#endif

#ifndef UTIME_OMIT
# define UTIME_OMIT  -2
#endif

**Comment by tkircher** [comment]
Incidentally, I also had to include the following in fuse-ext2.install.m:

#include <sys/_types.h>
#include <sys/_types/_uuid_t.h>

#ifndef _UUID_STRING_T
#define _UUID_STRING_T
typedef __darwin_uuid_string_t  uuid_string_t;
#endif /* _UUID_STRING_T */

**Comment by tkircher** [comment]
Looks like this is when MacOS support was broken:

https://github.com/alperakcan/fuse-ext2/commit/d7c145c0964ed4013597b04cb21a70f9d47898f3

**Comment by palbarede** [comment]
Hello.  I tried the patches but I still have the same errors.

`gcc -DHAVE_CONFIG_H -I. -I..    -Wall -DHAVE_CONFIG_H -I/usr/local/include -D__FreeBSD__=10 -idirafter/opt/gnu/include -idirafter/usr/local/include/osxfuse/ -MT fuse_ext2-op_utimens.o -MD -MP -MF .deps/fuse_ext2-op_utimens.Tpo -c -o fuse_ext2-op_utimens.o `test -f 'op_utimens.c' || echo './'`op_utimens.c
op_utimens.c:45:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[0].tv_nsec != UTIME_OMIT)
                             ^
op_utimens.c:47:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[1].tv_nsec != UTIME_OMIT)
                             ^
2 errors generated.
make[2]: *** [fuse_ext2-op_utimens.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Making install in fuse-ext2
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -DHAVE_CONFIG_H -I/usr/local/include -D__FreeBSD__=10 -idirafter/opt/gnu/include -idirafter/usr/local/include/osxfuse/ -MT fuse_ext2-op_utimens.o -MD -MP -MF .deps/fuse_ext2-op_utimens.Tpo -c -o fuse_ext2-op_utimens.o `test -f 'op_utimens.c' || echo './'`op_utimens.c
op_utimens.c:45:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[0].tv_nsec != UTIME_OMIT)
                             ^
op_utimens.c:47:23: error: use of undeclared identifier 'UTIME_OMIT'
        if (tv[1].tv_nsec != UTIME_OMIT)
                             ^
2 errors generated.
make[1]: *** [fuse_ext2-op_utimens.o] Error 1
make: *** [install-recursive] Error 1`

**Comment by palbarede** [comment]
Those files appear twice in the bundle.  The ones to be modified are in 
fuse-ext2-master/fuse-ext2.build/fuse-ext2/fuse-ext2/

**Comment by phil-blain** [comment]
I'm on macOS 10.11 and here are the steps that I used to get fuse-ext2 to build (hopefully simpler than the script in the README:
~~~bash
# install the dependencies using Homebrew
brew install e2fsprogs automake autoconf libtool # m4 from the system is OK
# e2fsprogs installs a 'uuid.h' header that shadows the system one and is not complete; move it out of the way
mv /usr/local/opt/e2fsprogs/include/uuid /usr/local/opt/e2fsprogs/include/uuid.back
# Make sure the configure script and Makefile have all the variable they need
export CPPFLAGS="-I/usr/local/include/osxfuse/ -I/usr/local/opt/e2fsprogs/include"
export LDFLAGS="-L/usr/local/opt/e2fsprogs/lib"
# Apply the fix from @tkircher above, just for fuse-ext2.h (see below)

./configure
make
~~~

The patch to be applied:
```diff
diff --git a/fuse-ext2/fuse-ext2.h b/fuse-ext2/fuse-ext2.h
index 07fd1db..2bc3331 100644
--- a/fuse-ext2/fuse-ext2.h
+++ b/fuse-ext2/fuse-ext2.h
@@ -57,6 +57,14 @@ errcode_t ext2fs_file_close2(ext2_file_t file, void (*close_callback) (struct ex
 /* max timeout to flush bitmaps, to reduce inconsistencies */
 #define FLUSH_BITMAPS_TIMEOUT 10
 
+#ifndef UTIME_NOW
+#define UTIME_NOW -1
+#endif
+
+#ifndef UTIME_OMIT
+#define UTIME_OMIT -2
+#endif
+
 struct extfs_data {
 	unsigned char debug;
 	unsigned char silent;
```
